server {
    listen 80;

    # Frontend
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Backend (API Gateway)
    location /auth/ {
        proxy_pass http://api_gateway:5000/auth/;
    }

    location /health {
        proxy_pass http://api_gateway:5000/health;
    }
}